name: CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]
  workflow_dispatch: 
    branch: [ "*" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: ./configure
      run: ./configure
      
    - name: Compile UnitTest
      run: g++ -o UnitTest UnitTest.cpp

    - name: Run UnitTest
      run: ./UnitTest

    - name: Run distcheck
      run: make check

    - name: Run distcheck
      run: make distcheck

    - name: Log in to dockerhub
      run: docker login -u ${{ vars.DOCKER_USERNAME }} -p {{ secrets.DOCKER_TOKEN }}

    - name: Build Dockerfile image
      run: docker build --platform=linux/amd64 -t ilyamaluk/devops --push .
