     name: Build

     on: [push, pull_request]

     jobs:
       build:
         runs-on: ubuntu-latest

         steps:
         - uses: actions/checkout@v3
         - name: Prepare Build Environment
           run: |
             sudo apt-get update
             sudo apt-get install -y autotools-dev automake devscripts debhelper
         - name: Generate Build System
           run: |
             autoreconf --install
             ./configure
         - name: Build
           run: |
             make
     
