name: CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Compile UnitTest
      run: g++ -o UnitTest UnitTest.cpp

    - name: Log in to Docker Hub
      env:
        DOCKER_USERNAME: ${{ vars.DOCKER_USERNAME }}
        DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
      run: |
        echo $DOCKER_TOKEN | docker login -u $DOCKER_USERNAME --password-stdin

    - name: Build Dockerfile image
      run: docker build --platform=linux/amd64 -t ilyamaluk/devops --push .
