name: CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Compile UnitTest
      run: g++ -o UnitTest UnitTest.cpp

    - name: Log in to Docker Hub
      run: docker login -u "${{ vars.DOCKER_USERNAME }}" -p "{{ "secrets.DOCKER_TOKEN" }}"

    - name: Build Dockerfile image
      run: docker build --platform=linux/amd64 -t ilyamaluk/devops --push .
