name: CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Make Server executable
      run: chmod +x lab2/lab2/HTTP_server

    - name: Make UnitTest executable
      run: chmod +x lab2/lab2/UnitTest

    - name: Run UnitTest
      run: |
        cd lab2/lab2/
        ./UnitTest

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ vars.DOCKER_USERNAME }}" --password-stdin

    - name: Build Dockerfile image
      run: docker build --platform=linux/amd64 -t ilyamaluk/devops --push .
